export { default as LogoSvg } from './icons/logo.svg'
export { default as SmileySvg } from './icons/smiley.svg'
export { default as MusicSvg } from './icons/music.svg'
export { default as CameraSvg } from './icons/camera.svg'
export { default as CalendarSvg } from './icons/calendar.svg'
export { default as ExitSvg } from './icons/exit.svg'
export { default as InfoSvg } from './icons/info.svg'
export { default as LanguageSvg } from './icons/language.svg'
export { default as LanguageSettingSvg } from './icons/language-setting.svg'
export { default as MessageSvg } from './icons/message.svg'
export { default as SettingSvg } from './icons/setting.svg'
export { default as SecuredSvg } from './icons/secured.svg'
export { default as SearchSvg } from './icons/search.svg'
export { default as CheckReadSvg } from './icons/check-read.svg'
export { default as CheckSendSvg } from './icons/check-send.svg'
export { default as MessageVectorSvg } from './icons/message-vector.svg'
export { default as SendSvg } from './icons/send.svg'
export { default as ArrowSvg } from './icons/arrow.svg'
export { default as MicroSvg } from './icons/micro.svg'
export { default as TrashSvg } from './icons/trash.svg'
export { default as ClipSvg } from './icons/clip.svg'
export { default as ImageSvg } from './icons/image.svg'
export { default as FileSvg } from './icons/file.svg'
export { default as DownloadSvg } from './icons/download.svg'
export { default as CloseSvg } from './icons/close.svg'
export { default as ThemeSvg} from './icons/theme.svg'
export { default as VideoOnSvg} from './icons/video-on.svg'
export { default as VideoOffSvg} from './icons/video-off.svg'
export { default as CallSvg} from './icons/call.svg'
export { default as MicroOnSvg} from './icons/micro-on.svg'
export { default as MicroOffSvg} from './icons/micro-off.svg'
export { default as PlaySvg} from './icons/play.svg'
export { default as PauseSvg} from './icons/pause.svg'
export { default as PencilSvg} from './icons/pencil.svg'
export { default as ProfileCameraSvg} from './icons/profile-camera.svg'